/*
Curso: ngenharia de Software - UniEVANGÉLICA

Disciplina: Sistemas Gerenciadores de Banco de Dados 

Dev: Guilherme de Moura Santos - 2110362

Data: 27/03/2023
*/

INSERT INTO personagem (nome_personagem, idade, sexo, habilidades, descricao)
VALUES
        ('Joel', 50, 'M', 'Combate corpo a corpo, tiro', 'Sobrevivente experiente e amargurado pela perda da filha.'),
        ('Ellie', 14, 'F', 'Furtividade, arco e flecha', 'Imune ao vírus Cordyceps, tornando-se uma das últimas esperanças da humanidade.'),
        ('Tommy', 48, 'M', 'Combate tático, liderança', 'Irmão mais novo de Joel e líder da resistência em Jackson.'),
        ('Maria', 38, 'F', 'Estratégia, comunicação', 'Esposa de Tommy e figura importante na liderança da resistência.'),
        ('Henry', 28, 'M', 'Armas de fogo, bom relacionamento com irmão', 'Irmão mais velho de Sam, é o responsável por protegê-lo em uma jornada pela sobrevivência.'),
        ('Sam', 12, 'M', 'Agilidade, furtividade', 'Irmão mais novo de Henry, é inocente e vulnerável em um mundo pós-apocalíptico.'),
        ('David', 43, 'M', 'Persuasão, liderança', 'Líder de um grupo de sobreviventes canibais.'),
        ('Tess', 36, 'F', 'Negociação, combate', 'Parceira de negócios de Joel e sobrevivente em um mundo cruel.'),
        ('Bill', 52, 'M', 'Conhecimento do terreno, armadilhas', 'Recluso que vive em uma cidade abandonada, ajuda Joel e Ellie a conseguir um carro.'),
        ('Riley', 16, 'F', 'Furtividade, combate corpo a corpo', 'Amiga de Ellie que a ajuda em uma aventura no mundo pós-apocalíptico.'),
        ('Marlene', 40, 'F', 'Liderança, negociação', 'Líder do grupo rebelde "Os Vagalumes", que busca encontrar uma cura para o vírus Cordyceps.'),
        ('Samuel', 42, 'M', 'Conhecimento do terreno, armas de fogo', 'Caçador que ensina a Joel e Ellie como sobreviver em um mundo hostil.'),
        ('Nora', 25, 'F', 'Combate corpo a corpo, tiro', 'Membro dos Vagalumes capturada pelos Serafitas.'),
        ('Lev', 13, 'M', 'Furtividade, arco e flecha', 'Serafita que desertou após ter sido forçado a matar a irmã por causa de sua orientação sexual.'),
        ('Yara', 16, 'F', 'Combate corpo a corpo, tiro', 'Irmã de Lev e Serafita que também desertou após a morte de sua mãe.'),
        ('Isaac', 50, 'M', 'Liderança, estratégia', 'Líder dos Serafitas, uma facção religiosa que domina a cidade.'),
        ('Abby', 21, 'F', 'Combate corpo a corpo, força física', 'Filha do médico que Joel matou no primeiro jogo, em busca de vingança.'),
        ('Owen', 27, 'M', 'Natação, furtividade', 'Membro dos WLF e ex-namorado de Abby.'),
        ('Mel', 28, 'F', 'Medicina, negociação', 'Médica dos WLF e grávida de Owen.'),
        ('Manny', 28, 'M', 'Combate corpo a corpo, armas de fogo', 'Membro dos WLF e amigo de Abby.'),
        ('Jordan', 36, 'M', 'Combate corpo a corpo, liderança', 'Líder dos WLF no hospital.'),
        ('Leah', 20, 'F', 'Furtividade, arco e flecha', 'Membro dos WLF que se opõe às táticas violentas da facção.'),
        ('Jerry', 49, 'M', 'Medicina, ciência', 'Médico dos Vagalumes que busca uma cura para o vírus Cordyceps.'),
        ('Ellie (Adulto)', 19, 'F', 'Combate corpo a corpo, arco e flecha', 'Protagonista do segundo jogo, em busca de vingança contra Abby.'),
        ('Dina', 18, 'F', 'Combate corpo a corpo, arco e flecha', 'Namorada de Ellie e membro dos Vagalumes.'),
        ('Jesse', 21, 'M', 'Armas de fogo, estratégia', 'Amigo de Ellie e membro dos Vagalumes.'),
        ('Joel (Jovem)', 30, 'M', 'Combate corpo a corpo, tiro', 'Protagonista do primeiro jogo, é um caçador solitário até conhecer Ellie.'),
        ('Tommy (Jovem)', 25, 'M', 'Armas de fogo, liderança', 'Irmão mais novo de Joel e membro dos Caçadores de Jackson.'),
        ('Sarah', 12, 'F', 'N/A', 'Filha de Joel que é morta no início do primeiro jogo, desencadeando a história.'),
        ('Marlene (Jovem)', 22, 'F', 'Combate corpo a corpo, liderança', 'Líder dos Vagalumes antes de Marlene no primeiro jogo.'),
        ('Robert', 35, 'M', 'Negociação, suborno', 'Contrabandista que trai Joel e Tess.'),
        ('David (Infância)', 12, 'M', 'Persuasão, liderança', 'Líder de um grupo de sobreviventes canibais na infância, antes dos eventos do primeiro jogo.'),
        ('Ishmael', 36, 'M', 'Conhecimento do terreno, sobrevivência', 'Sobrevivente solitário que deixa diários ao longo do primeiro jogo.'),
        ('Sam (Infância)', 7, 'M', 'N/A', 'Irmão mais novo de Henry na infância, antes dos eventos do primeiro jogo.'),
        ('Henry (Infância)', 10, 'M', 'N/A', 'Irmão mais velho de Sam na infância, antes dos eventos do primeiro jogo.'),
        ('Frank', 42, 'M', 'Armas de fogo, contrabando', 'Contrabandista que Joel e Tess encontram no primeiro jogo.'),
        ('Callus', 2, 'M', 'N/A', 'Cavalo de Dina em The Last of Us Part II.'),
        ('Alice', 5, 'F', 'N/A', 'Cachorra de Ellie em The Last of Us Part II.'),
        ('Bear', 4, 'M', 'N/A', 'Cachorro de Jesse em The Last of Us Part II.'),
        ('Manny (Infância)', 8, 'M', 'N/A', 'Membro dos Caçadores de Jackson na infância, antes dos eventos do primeiro jogo.'),
        ('Winston', 35, 'M', 'Armas de fogo, liderança', 'Líder dos Caçadores de Jackson no primeiro jogo.'),
        ('Maria (Jovem)', 30, 'F', 'Liderança, comunicação', 'Esposa de Tommy na infância, antes dos eventos do primeiro jogo.'),
        ('Eugene', 30, 'M', 'Ciência, fabricação', 'Sobrevivente que ajuda Joel e Ellie no segundo jogo, antes de ser morto por Abby.'),
        ('Carla', 25, 'F', 'Furtividade, engenharia', 'Sobrevivente habilidosa em construções e dispositivos eletrônicos.'),
        ('Martin', 32, 'M', 'Combate corpo a corpo, estratégia', 'Líder da resistência contra os zumbis e protetor de uma pequena comunidade.'),
        ('Luana', 27, 'F', 'Armas de fogo, liderança', 'Líder de um grupo de sobreviventes em uma cidade dominada por zumbis.'),
        ('Rafael', 23, 'M', 'Furtividade, comunicação', 'Sobrevivente hábil em se comunicar com outras pessoas e recolher informações valiosas.'),
        ('Mariana', 29, 'F', 'Combate corpo a corpo, agilidade', 'Ex-militar que se juntou a um grupo de sobreviventes após a queda da civilização.'),
        ('Lucas', 16, 'M', 'Arco e flecha, furtividade', 'Jovem sobrevivente que vive nas ruas e se tornou hábil em furtividade e caça.'),
        ('Clara', 30, 'F', 'Negociação, estratégia', 'Sobrevivente que lidera um grupo de comerciantes em uma cidade pós-apocalíptica.'),
        ('Mateus', 40, 'M', 'Combate corpo a corpo, liderança', 'Ex-policial que lidera um grupo de sobreviventes em busca de um lugar seguro.'),
        ('Larissa', 19, 'F', 'Armas de fogo, furtividade', 'Sobrevivente que se juntou a um grupo de caçadores de recompensas após perder sua família.'),
        ('Rodrigo', 28, 'M', 'Combate corpo a corpo, força física', 'Sobrevivente que se tornou forte fisicamente após viver em uma cidade pós-apocalíptica.'),
        ('Isabela', 23, 'F', 'Furtividade, engenharia', 'Sobrevivente que se juntou a um grupo de engenheiros em busca de um lugar seguro para viver.'),
        ('Felipe', 34, 'M', 'Armas de fogo, estratégia', 'Ex-militar que lidera um grupo de sobreviventes em busca de um lugar seguro para viver.'),
        ('Juliana', 28, 'F', 'Negociação, liderança', 'Sobrevivente que lidera um grupo de comerciantes em busca de um lugar seguro para viver.'),
        ('Thiago', 22, 'M', 'Furtividade, arco e flecha', 'Sobrevivente que se juntou a um grupo de caçadores após a queda da civilização.'),
        ('Gabriela', 25, 'F', 'Armas de fogo, furtividade', 'Sobrevivente que se juntou a um grupo de caçadores de recompensas após perder sua família.'),
        ('Henry (Jovem)', 22, 'M', 'Armas de fogo, bom relacionamento com irmão', 'Irmão mais velho de Sam, é o responsável por protegê-lo em uma jornada pela sobrevivência.'),
        ('Sam (Jovem)', 8, 'M', 'Agilidade, furtividade', 'Irmão mais novo de Henry, é inocente e vulnerável em um mundo pós-apocalíptico.'),
        ('Ishmael', 35, 'M', 'Conhecimento do terreno, armas de fogo', 'Sobrevivente que lidera uma pequena comunidade.'),
        ('Reuben', 50, 'M', 'Negociação, liderança', 'Líder da colônia Hillcrest.'),
        ('Harvey', 30, 'M', 'Armas de fogo, liderança', 'Líder do grupo de sobreviventes de Seattle.'),
        ('Walter', 43, 'M', 'Conhecimento do terreno, armadilhas', 'Sobrevivente que vive em um forte, oferece suprimentos para Ellie e Joel.'),
        ('Winston', 50, 'M', 'Estratégia, liderança', 'Líder da colônia Lakeside.'),
        ('Maria (Jovem)', 25, 'F', 'Combate tático, estratégia', 'Esposa de Tommy e membro dos Caçadores de Jackson.'),
        ('Jerry Anderson', 55, 'M', 'Medicina, ciência', 'Cientista que trabalha para a WLF na produção de vacinas.'),
        ('Kara', 32, 'F', 'Combate corpo a corpo, furtividade', 'Membro dos WLF que ajuda Abby.'),
        ('Oscar', 60, 'M', 'Conhecimento do terreno, armas de fogo', 'Sobrevivente que ajuda Joel e Ellie a chegar a Tommy.'),
        ('Janey', 35, 'F', 'Negociação, comunicação', 'Sobrevivente que ajuda Joel e Ellie a encontrar mantimentos em uma zona de quarentena.'),
        ('Eugene', 29, 'M', 'Ciência, eletrônica', 'Sobrevivente que vive em uma cabana e ajuda Abby e Lev com equipamentos eletrônicos.'),
        ('Dani', 22, 'F', 'Combate corpo a corpo, estratégia', 'Membro dos Vagalumes que ajuda Ellie em sua vingança.'),
        ('Javi', 19, 'M', 'Combate corpo a corpo, tiro', 'Membro dos WLF que ajuda Abby e Lev a chegar ao hospital.'),
        ('Emily', 29, 'F', 'Medicina, ciência', 'Médica dos WLF que ajuda Abby em sua vingança.'),
        ('Nick', 29, 'M', 'Armas de fogo, liderança', 'Membro dos WLF que ajuda Abby e Lev em sua jornada.'),
        ('Benjamin Billingham', 53, 'M', 'Negociação, liderança', 'Líder da comunidade de sobreviventes em Jackson, substitui Tommy como líder da comunidade.'),
        ('Sarah', 12, 'F', 'Nenhuma', 'Filha de Joel, morta no início do primeiro jogo pela infecção do vírus Cordyceps.'),
        ('Ishmael', 36, 'M', 'Sobrevivência, estratégia', 'Sobrevivente que lidera um grupo em busca de uma nova comunidade em "The Last of Us: American Dreams"'),
        ('Christine', 20, 'F', 'Nenhuma', 'Jovem sobrevivente que encontra Ellie em "The Last of Us: American Dreams"'),
        ('Ethan', 28, 'M', 'Armas de fogo, liderança', 'Líder do grupo dos Caçadores em "The Last of Us: American Dreams"'),
        ('Winston', 54, 'M', 'Nenhuma', 'Líder do grupo dos Vagalumes em Pittsburgh.'),
        ('Henry (Zumbi)', N/A, 'M', 'Nenhuma', 'Versão zumbi de Henry, morto após se infectar.'),
        ('Sam (Zumbi)', N/A, 'M', 'Nenhuma', 'Versão zumbi de Sam, morto após se infectar.'),
        ('James', 24, 'M', 'Nenhuma', 'Sobrevivente que encontra Ellie e Dina no caminho.'),
        ('Yara (Zumbi)', N/A, 'F', 'Nenhuma', 'Versão zumbi de Yara, morta após se infectar.'),
        ('Lev (Zumbi)', N/A, 'M', 'Nenhuma', 'Versão zumbi de Lev, morto após se infectar.'),
        ('Abby (Zumbi)', N/A, 'F', 'Nenhuma', 'Versão zumbi de Abby, morta após se infectar.'),
        ('Owen (Zumbi)', N/A, 'M', 'Nenhuma', 'Versão zumbi de Owen, morto após se infectar.'),
        ('Mel (Zumbi)', N/A, 'F', 'Nenhuma', 'Versão zumbi de Mel, morta após se infectar.'),
        ('Manny (Zumbi)', N/A, 'M', 'Nenhuma', 'Versão zumbi de Manny, morto após se infectar.'),
        ('Jordan (Zumbi)', N/A, 'M', 'Nenhuma', 'Versão zumbi de Jordan, morto após se infectar.'),
        ('Leah (Zumbi)', N/A, 'F', 'Nenhuma', 'Versão zumbi de Leah, morta após se infectar.'),
        ('Jerry (Zumbi)', N/A, 'M', 'Nenhuma', 'Versão zumbi de Jerry, morto após se infectar.'),
        ('Ellie (Zumbi)', N/A, 'F', 'Nenhuma', 'Versão zumbi de Ellie, morta após se infectar.'),
        ('Joel (Zumbi)', N/A, 'M', 'Nenhuma', 'Versão zumbi de Joel, morto após se infectar.'),
        ('Maria (Zumbi)', N/A, 'F', 'Nenhuma', 'Versão zumbi de Maria, morta após se infectar.'),
        ('Christine(Zumbi)', N/A, 'F', 'Nenhuma', 'Versão zumbi de Maria, morta após se infectar.'),
        ('Sarah(Zumbi)', N/A, 'F', 'Nenhuma', 'Versão zumbi de Maria, morta após se infectar.');

SELECT AVG(idade) FROM personagem;
